cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
tap "phinze/cask"
tap "thoughtbot/formulae"
tap "heroku/brew"

# Libs
brew "gdb"
brew "gdbm"
brew "gettext"
brew "gmp"
brew "icu4c"
brew "libffi"
brew "libpng"
brew "libtermkey"
brew "libtool"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "libyaml"
brew "pcre"
brew "readline"
brew "unibilium"
brew "xz"

# Languages
cask "java" # Java First for Groovy
brew "go"
brew "lua"
brew "the_silver_searcher"
brew "elixir"
brew "node"
brew "nvm"
brew "yarn"
brew "python"
brew "chruby"
brew "ruby-install", args: ["HEAD"]

# Development
brew "ctags"
brew "direnv"
brew "fzf"
brew "git"
brew "git-hooks"
brew "groovy"
brew "jq"
brew "mkcert"
brew "neovim"
brew "rcm"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "zsh"

# Helpful Tools
brew "autoconf"
brew "autojump"
brew "automake"
brew "bash"
brew "ccat"
brew "cmake"
brew "coreutils"
brew "editorconfig"
brew "entr"
brew "httpie"
brew "heroku"
brew "imagemagick"
brew "imagemagick@6"
brew "msgpack"
brew "mysql@5.7"
brew "oniguruma"
brew "openssl@1.1"
brew "pandoc"
brew "sqlite"
brew "ssh-copy-id"
brew "tree"
brew "watch"
brew "wget"

# Fun
brew "fortune", args: ["without-offensive"]

# macOS Applications
cask "alfred"
cask "anki"
cask "bartender"
cask "docker"
cask "evernote"
cask "firefox"
cask "focus"
cask "gitup"
cask "google-backup-and-sync"
cask "google-chrome"
cask "intellij-idea"
cask "iterm2"
cask "kap"
cask "macdown"
cask "mojibar"
cask "numi"
cask "postgres"
cask "postman"
cask "psequel"
cask "skype"
cask "slack"
cask "soundflower"
cask "spotify"
cask "sublime-merge"
cask "vagrant"
