tap "dopplerhq/cli"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
tap "thoughtbot/formulae"
brew "gdbm"
brew "libyaml"
brew "readline"
brew "xz"
brew "ansible"
brew "augeas"
brew "autoconf"
brew "autojump"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bison"
brew "bzip2"
brew "ccat"
brew "dialog"
brew "certbot"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "openldap"
brew "direnv"
brew "dnsmasq", restart_service: true
brew "editorconfig"
brew "entr"
brew "libpng"
brew "fortune"
brew "libtool"
brew "unixodbc"
brew "fzf"
brew "gdb"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-flow"
brew "libffi"
brew "pcre"
brew "glib"
brew "gmp"
brew "pkg-config"
brew "guile"
brew "libksba"
brew "gnupg"
brew "go"
brew "httpie"
brew "icu4c"
brew "shared-mime-info"
brew "libheif"
brew "python@3.8"
brew "imagemagick"
brew "imagemagick@6"
brew "oniguruma"
brew "jq"
brew "lastpass-cli"
brew "libiconv"
brew "libidn"
brew "libmemcached"
brew "libsodium"
brew "unibilium"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "lua"
brew "mas"
brew "memcached"
brew "mkcert"
brew "msgpack"
brew "mysql@5.7"
brew "nginx", restart_service: true
brew "node"
brew "nss"
brew "pandoc"
brew "php", restart_service: true
brew "pinentry-mac"
brew "pwgen"
brew "re2c"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ruby"
brew "speedtest-cli"
brew "ssh-copy-id"
brew "switchaudio-osx"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "dopplerhq/cli/doppler"
brew "heroku/brew/heroku"
brew "thoughtbot/formulae/rcm"
cask "adoptopenjdk"
cask "alfred"
cask "anki"
cask "bartender"
cask "chromedriver"
cask "docker"
cask "firefox"
cask "focus"
cask "font-courier-prime-code"
cask "font-fira-code"
cask "forticlient"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "kap"
cask "kindle"
cask "postgres"
cask "postico"
cask "postman"
cask "robo-3t"
cask "sequel-pro"
cask "skype"
cask "spotify"
cask "sublime-merge"
cask "toggl-track"
cask "vagrant"
cask "visual-studio-code"
cask "vlc"
cask "workflowy"
mas "BetterSnapTool", id: 417375580
mas "Harvest", id: 506189836
mas "iMovie", id: 408981434
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
