#!/bin/bash
# vim: filetype=sh

set -e

readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(greadlink -m $(dirname $0))
readonly ARGS="$@"

readonly ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD)

readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

run() {
  local cmd=$@

  echo -e "${YELLOW}\$ $cmd${NC}"
  command $cmd
}

main() {
  local target=$1

  if [[ "$target" != "$ORIGINAL_BRANCH" ]]
  then
    run "git checkout $target"
  fi

  run "git fetch"
  run "git reset --hard origin/$target"

  if [ "$target" != "$ORIGINAL_BRANCH" ]
  then
    run "git checkout $ORIGINAL_BRANCH"
  fi
}

main $ARGS
