#!/usr/bin/env ruby

system "git submodule update"
system "git submodule foreach git pull origin master"

submodules = `git status | grep "modified.*\(new commits\)" | awk '{print $3}'`.split("\n").map(&:strip)

if submodules.any?
  puts "Updating #{submodules.size} submodule(s)..."
  submodules.each { |name| system "git add #{name}" }
  commit_message = "Updating #{submodules.size} submodule(s):\n"
  commit_message << submodules.map { |name| "* #{name}" }.join("\n")
  system "git commit -m '#{commit_message}'"
else
  puts "No submodules to update"
end

