#!/usr/bin/env ruby

EMOTICONS = %w[ (happy) (L) (inlove) :* (sun) ]

chosen_emoticons = EMOTICONS.sample(rand(2..EMOTICONS.length))
min_lines = 25
max_lines = 45
in_groups_of = ->(range, emo){ range.map { emo }  }

groups = chosen_emoticons.collect do |emoticon|
  in_groups_of.(2..8, emoticon)
end

result = []
rand(min_lines..max_lines).times do |n|
  result << groups
end

$stdout.write result.flatten(4).join
