#!/bin/zsh

if [ ! -e "$HOME/.zprezto" ]; then
  echo "==> Installing Prezto..."
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" &> /dev/null
  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    if [ ! -f "$HOME/.${rcfile:t}" ]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    fi
  done
else
  echo "==> Updating Prezto..."
  cd "${ZDOTDIR:-$HOME}/.zprezto" &> /dev/null
  git pull >/dev/null 2>&1
  git submodule update >/dev/null 2>&1
  cd - &> /dev/null
fi

if [ ! -e "$HOME/.vim/autoload/plug.vim" ]; then
  echo "==> Installing vim-plug"
else
  echo "==> Updating vim-plug"
fi

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "==> Preparing minpac for Vim"
mkdir -p ~/.vim/pack/minpac/opt
cd "$HOME/.vim/pack/minpac/opt" &> /dev/null
git clone https://github.com/k-takata/minpac.git
cd - &> /dev/null


# For development
brew install vim --override-system-vi --with-lua
brew install tmux

# Setup Ruby Version Manager
brew install chruby
brew install ruby-install --HEAD

# Essential development packages
brew install git
brew install git-hooks
brew install the_silver_searcher
brew install thoughtbot/formulae/rcm
brew install thoughtbot/formulae/pick

# Background services
brew install memcached
brew install openssl
# brew install redis

# Extra fun stuff
brew install jq
brew install htop-osx
brew install heroku-toolbelt
# brew install nviennot/tmate/tmate
brew install tree
brew install pandoc
brew install xmlstarlet
brew install ssh-copy-id

# Setup other useful tools/langs
brew install ack
brew install bash
brew install ccat
brew install direnv
brew install elixir
brew install heroku-toolbelt
brew install the_silver_searcher
brew install wget
brew install zsh
brew install lastpass-cli --with-pinentry --with-doc

# OSX Apps
brew install phinze/cask/brew-cask
brew cask install hammerspoon 2> /dev/null

# brew cask install audacity 2> /dev/null
# brew cask install dropbox 2> /dev/null
# brew cask install google-chrome 2> /dev/null
# brew cask install google-chrome-canary 2> /dev/null
# brew cask install iterm2 2> /dev/null
# brew cask install jing 2> /dev/null
# brew cask install sublime-text 2> /dev/null
# brew cask install sequel-pro 2> /dev/null
# brew cask install vagrant 2> /dev/null
# brew cask install virtualbox 2> /dev/null
# brew cask install vlc 2> /dev/null

# Fun OSX Quick Look plugins
brew cask install betterzipql 2> /dev/null
brew cask install qlcolorcode 2> /dev/null
brew cask install qlmarkdown 2> /dev/null
brew cask install qlprettypatch 2> /dev/null
brew cask install qlstephen 2> /dev/null
brew cask install quicklook-csv 2> /dev/null
brew cask install quicklook-json 2> /dev/null
brew cask install suspicious-package 2> /dev/null
brew cask install webp-quicklook 2> /dev/null

echo "==> Adding $HOME/.localbin directory for other scripts"
mkdir "$HOME/.localbin" >/dev/null 2>&1

echo "==> Installing vim bundles...";
vim +PluginInstall +qall

echo "==> Installing latest version of Ruby"
ruby-install ruby
