#!/bin/zsh

if [ ! -e "$HOME/.zprezto" ]; then
  echo "Installing Prezto..."
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" &> /dev/null
  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    if [ ! -f "$HOME/.${rcfile:t}" ]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    fi
  done
fi

if [ ! -e "$HOME/.vim/bundle/vundle" ]; then
  echo "Installing Vundle..."
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle &> /dev/null
fi

# For development
brew install vim --override-system-vi --with-lua
brew install tmux

# Setup Ruby Version Manager
brew install rbenv
brew install ruby-build --HEAD

# Setup other useful tools/langs
brew install ack
brew install bash
brew install direnv
brew install elixir
brew install heroku-toolbelt
brew install the_silver_searcher
brew install wget
brew install zsh
brew install lastpass-cli --with-pinentry --with-doc

echo "Installing vim bundles...";
vim +PluginInstall +qall

