#!/usr/bin/env zsh
# vim: filetype=zsh

set -e

source ${0:a:h}/helpers

main() {
  checkGit
  checkBrew
  checkRcm
  checkZprezto
  checkPhpbrew
  checkAsdf
  checkAsdfPlugin "ruby"
  checkAsdfPlugin "nodejs"
  checkAsdfPlugin "deno"
  checkAsdfPlugin "tmux"
  checkAsdfPlugin "php"
  checkTmux
  checkTpm
  checkVagrant
  checkVagrantPlugins
  checkDotfilesRepo
}

main $ARGS
