#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# shellcheck source=./exe/helpers
source "${DIR}/helpers"


main() {
  checkGit
  checkBrew
  checkRcm
  checkZprezto
  checkPhpbrew
  checkAsdf
  checkAsdfPlugin "ruby"
  checkAsdfPlugin "nodejs"
  checkAsdfPlugin "deno"
  checkAsdfPlugin "tmux"
  checkAsdfPlugin "php"
  checkTmux
  checkTpm
  checkVagrant
  checkVagrantPlugins
  checkDotfilesRepo
}

main
