#!/usr/bin/env zsh
# vim: filetype=zsh

set -e

source $HOME/.dotfiles/exe/helpers

install_brews() {
  say "Homebrew Bundling..."
  pushd $HOME/.dotfiles &> /dev/null
  brew bundle --no-upgrade
  popd &> /dev/null
  say_done
}

install_vim_minpac() {
  say "Preparing minpac for Vim"
  if [ ! -d "$HOME/.config/nvim/pack/minpac/opt/minpac" ]; then
    say "Cloning minpac for neovim"

    mkdir -p ~/.config/nvim/pack/minpac/opt/
    git clone https://github.com/k-takata/minpac.git "$HOME/.config/nvim/pack/minpac/opt/minpac"

    say_done
  else
    announce "Updating minpac"

    pushd "$HOME/.config/nvim/pack/minpac/opt/minpac" &> /dev/null
    git pull

    popd &> /dev/null
  fi

  popd &> /dev/null
  say_done
}

main() {
  install_brews && echo
  install_vim_minpac && echo

  say "Dependencies prepared!"
}

main
