#!/usr/bin/env zsh
# vim: filetype=zsh

readonly GREEN='\033[0;32m'
readonly BLUE='\033[0;34m'
readonly BGREEN='\033[1;32m'
readonly BCYAN='\033[1;36m'
readonly NC='\033[0m'

say() {
  local statement=$@

  echo -e "${BCYAN}==> ${NC}$statement${NC}"
}

announce() {
  local statement=$@
  echo -e "${BCYAN}==>${NC}${BGGREEN} $statement${NC}"
}

say_done() {
  echo -e "${BCYAN}==>${NC}${BGREEN} Done!${NC}"
}
