#!/usr/bin/env bash
# vim: filetype=sh

set -e

# Ask for the administrator password upfront
sudo -v

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# shellcheck source=./exe/helpers
source "${DIR}/helpers"

main() {
  keepSudoAlive

  installHomebrew
  installEssentialBrews
  installAsdf
  installAsdfPlugins
  installVagrantPlugins
  installPhpbrew
  installZprezto
  installTpm

  installBrewfile
  installVimMinpac

  cloneRepo
  setupDotfiles
  setupStarship

  setupZshAsDefault
  setupMinpackPlugins
  installAsdfTools

  # . $HOME/.dotfiles/exe/macos

  echo
  logSuccess "Finished setting up the system"
}

main "$ARGS"
