#!/usr/bin/env zsh
# vim: filetype=zsh

set -e

# Ask for the administrator password upfront
sudo -v

source ${0:a:h}/helpers

main() {
  keepSudoAlive

  installHomebrew
  installEssentialBrews
  installVagrantPlugins
  installPhpbrew
  installZprezto
  installTpm
  installNvm

  installBrewfile
  installVimMinpac

  cloneRepo

  # . $HOME/.dotfiles/exe/setup
  # . $HOME/.dotfiles/exe/macos

  echo
  logSuccess "Finished installing"
}

main $ARGS
