#!/usr/bin/env zsh
# vim: filetype=zsh

source ${0:a:h}/helpers

set -e

setup_zsh_as_default() {
  if [ -f /usr/local/bin/zsh ]; then
    log "Setting zsh as default shell"
    sudo chsh -s $(which zsh) $(whoami)
  else
    announce "Homebrew zsh already set as default shell"
    logDone
  fi
}

setup_dotfiles() {
  log "Setting up dotfiles"
  rm -rf $HOME/.rcrc
  ln -s $HOME/.dotfiles/rcrc $HOME/.rcrc
  rcup

  log "Installing/updating minpac"
  mkdir -p ~/.config/nvim
  if [ ! -d ~/.config/nvim/pack/minpac/opt/minpac ]; then
    git clone https://github.com/k-takata/minpac.git \
      ~/.config/vvim/pack/minpac/opt/minpac
  else
    pushd ~/.config/vvim/pack/minpac/opt/minpac
    git pull
    popd
  fi


  rm -f $HOME/.config/nvim/init.vim
  ln -s $HOME/.vimrc $HOME/.config/nvim/init.vim

  logDone
}

setup_zpresto() {
  if [ ! -e "$HOME/.zprezto" ]; then
    log "Installing Prezto..."
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto" &> /dev/null
    setopt EXTENDED_GLOB
    for rcfile in $(find ~/.zprezto/runcoms | grep -v README.md); do
      if [ ! -f "$HOME/.${rcfile:t}" ]; then
        ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
      fi
    done
    logDone
  else
    log "Updating Prezto..."
    cd "${ZDOTDIR:-$HOME}/.zprezto" &> /dev/null
    git pull >/dev/null 2>&1
    git submodule update >/dev/null 2>&1
    cd - &> /dev/null
    logDone
  fi
}

setup_minpac_plugins() {
  log "Installing Vim plugins"
  nvim +PackUpdate +q && echo
  logDone
}

setup_vagrant() {
  local vagrantplugins=$(vagrant plugin list | grep -ic "parallels" -eq "1")

  if [[ $vagrantparallels =~ /vagrant-parallels/ ]]; then
    log "Installing Vagrant dependencies"
    vagrant plugin install vagrant-parallels
    vagrant plugin install vagrant-virtualbox
    logDone
  else
    announce "vagrant-parallels already setup"
  fi
}

main() {
  checkGit
  checkBrew
  checkRcm
  logDone
  # setup_zsh_as_default && echo
  # setup_dotfiles && echo
  # setup_zpresto && echo
  # setup_minpac_plugins && echo
  # setup_vagrant && echo
}

main
