#!/bin/zsh
# vim: filetype=zsh

set -e

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Don't need these right now, but maybe later on
# readonly PROGNAME=`basename $0`
# readonly PROGDIR=`/usr/bin/readlink -n $(dirname $0)`
readonly ARGS="$@"

readonly GREEN='\033[0;32m'
readonly BLUE='\033[0;34m'
readonly BGREEN='\033[1;32m'
readonly BCYAN='\033[1;36m'
readonly BWHITE='\033[1;37m'
readonly NC='\033[0m'

say() {
  local statement=$@

  echo -e "${BCYAN}==> ${BWHITE}$statement${NC}"
}

announce() {
  local statement=$@
  echo -e "${BCYAN}==>${NC}${GREEN} $statement${NC}"
}

say_done() {
  echo -e "${BCYAN}==>${NC}${BGREEN} Done!${NC}"
}

install_homebrew() {
  if [ ! -x "$(command -v brew)" ]; then
    say "Installing Homebrew"
    ruby <(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)
    say_done
  else
    announce "Homebrew already installed"
  fi
}

install_brews() {
  say "Installing main brews"
  brew install git neovim/neovim/neovim thoughtbot/formulae/rcm 2> /dev/null
  say_done
}

clone_repo_to_dotfiles() {
  local dir="$HOME/.dotfiles"

  if [ ! -d $dir ]; then
    say "Cloning dotfiles repository"
    git clone https://github.com/mdespuits/dotfiles.git $HOME/.dotfiles
    say_done
  else
    announce "Dotfiles repo already cloned."
  fi
}

install_vim_minpac() {
  say "Preparing minpac for Vim"
  if [ ! -d "$HOME/.config/nvim/pack/minpac/opt/minpac" ]; then
    say "Cloning minpac for neovim"

    mkdir -p ~/.config/nvim/pack/minpac/opt/
    git clone https://github.com/k-takata/minpac.git \
      $HOME/.config/nvim/pack/minpac/opt/minpac

    popd &> /dev/null
    say_done
  else
    announce "Updating minpac"

    pushd "$HOME/.config/nvim/pack/minpac/opt/minpac" &> /dev/null
    git pull

    popd &> /dev/null
  fi

  popd &> /dev/null
  say_done
}

brew_bundle() {
  say "Homebrew Bundling..."
  pushd $HOME/.dotfiles &> /dev/null
  brew bundle --no-upgrade
  popd &> /dev/null
  say_done
}

setup_zsh_as_default() {
  if [ -f /usr/local/bin/zsh ]; then
    say "Setting zsh as default shell"
    sudo chsh -s $(which zsh) $(whoami)
  else
    announce "Homebrew zsh already set as default shell"
    say_done
  fi
}

setup_dotfiles() {
  say "Setting up dotfiles"
  rm -rf $HOME/.rcrc
  ln -s $HOME/.dotfiles/rcrc ~/.rcrc
  rcup -v

  rm -f $HOME/.config/nvim/init.vim
  ln -s $HOME/.vimrc $HOME/.config/nvim/init.vim

  say_done
}

main() {
  install_homebrew && echo
  install_brews && echo
  install_vim_minpac && echo

  clone_repo_to_dotfiles && echo

  brew_bundle && echo

  setup_zsh_as_default && echo
  setup_dotfiles && echo

  say "Dependencies setup!"
}

main $ARGS
